# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Planit

on: 
  push:
    branches: [ main ]
  schedule:
  - cron: '30 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PLANIT_TOKEN }}
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Retrieve assignment information
      run: |
        python --version
        python main.py
      env:
        GRADESCOPE_USER: ${{ secrets.GRADESCOPE_USER }}
        GRADESCOPE_PASSWORD: ${{ secrets.GRADESCOPE_PASSWORD }}
    
    - name: Commit new outputs
      env:
        TOKEN: ${{ secrets.PLANIT_TOKEN }}
      run: |
        git add . || true
        git commit -m 'Updated assignments' || true
        git remote -v
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/Nick-Trigger/gradscopePlanner.git
        git remote -v
        git push origin main
        git push -f origin main:github-pages



